// Servo - Version: Latest 
#include <Servo.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "NodeMCUMotor"
  https://create.arduino.cc/cloud/things/11e15862-5152-4a08-80bc-c20877b01491 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool servoposleft;
  int speedadjust;
  bool servoposright;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

int speed = 0;
int *pspeed = &speed;

Servo servomtr;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  servomtr.attach(2);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

/*
  Since Servopos is READ_WRITE variable, onServoposChange() is
  executed every time a new value is received from IoT Cloud.
*/

void onServoposleftChange()  {
  // Add your code here to act upon Servoposleft change
  if (servoposleft){
    servomtr.write(89 - *pspeed);
  }
  else{
    servomtr.write(90);
  }
  
}

/*
  Since Servoposright is READ_WRITE variable, onServoposrightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onServoposrightChange()  {
  // Add your code here to act upon Servoposright change
    if (servoposright){
    servomtr.write(91 + *pspeed);
  }
  else{
    servomtr.write(90);
  }
  
}

/*
  Since Speedadjust is READ_WRITE variable, onSpeedadjustChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSpeedadjustChange()  {
  // Add your code here to act upon Speedadjust change
   *pspeed = speedadjust;
}

